run-name: Parameters

on:
  workflow_dispatch:

jobs:
  Parameters:
    name: Parameters
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        M: [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
        dim: [2, 3, 4, 5, 10]
        div: ['A', 'B', 'C', 'D']

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      
      - name: Configure repo
        run: |
          git config --global user.name 'FreitasDavid'
          git config --global user.email 'dfreitas022@gmail.com'
          git pull
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Execute models
        run: |
          python calculate.py div=${{ matrix.div }} M=${{ matrix.M }} dim=${{ matrix.dim }} > results_S${{ matrix.div }}_${{ matrix.M }}_${{ matrix.dim }}.txt
      
      - name: Send results
        run: |
          python send_results.py -p=${{ secrets.PASSWORD }} -u=${{ secrets.USER }} -s=${{ secrets.USER }}
